name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '9 17 * * *'
jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.2.1
        with:
          github_token: ${{ secrets.OBCRL_TOKEN }}
          owner: XTLS
          base: main
          head: main
